spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.141:13306/ams_basic?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.141:8849
  application:
    name: ams-basic
  mail:
    host: smtp.qq.com #邮箱服务器地址
    port: 587
    username: 1796899275@qq.com #用户名
    password: fjcgdkinwttebcea  #授权码
    properties:
      mail:
        smtp:
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000
logging:
  level:
    com.scu.ams.basic: debug

    com.scu.ams: debug
file-upload-path: ./ams-basic/src/main/java/com/scu/ams/basic/file

shiro:
  enabled: true
  annotations:
    enabled: true
